-- **************** SBO Plugin ***********************
----------------
-- Plugin Types
----------------
-- *** Items *** --
INSERT INTO SCEXPERTCONNECTPLUGINTYPES(PLUGINTYPEID,PLUGINTYPE,PLUGINNAME,ASSEMBLYDLL,CLASSNAME) 
VALUES(3,'SBO','SBO Items','SCExpertConnectSBOPlugin.dll','SCExpertConnectSBOPlugin.Items')

-- *** Cards *** --
INSERT INTO SCEXPERTCONNECTPLUGINTYPES(PLUGINTYPEID,PLUGINTYPE,PLUGINNAME,ASSEMBLYDLL,CLASSNAME) 
VALUES(4,'SBO','SBO Cards','SCExpertConnectSBOPlugin.dll','SCExpertConnectSBOPlugin.Cards')

-- *** Documents *** --
INSERT INTO SCEXPERTCONNECTPLUGINTYPES(PLUGINTYPEID,PLUGINTYPE,PLUGINNAME,ASSEMBLYDLL,CLASSNAME) 
VALUES(5,'SBO','SBO Documents','SCExpertConnectSBOPlugin.dll','SCExpertConnectSBOPlugin.Documents')

-- *** Stock Transfers *** --
INSERT INTO SCEXPERTCONNECTPLUGINTYPES(PLUGINTYPEID,PLUGINTYPE,PLUGINNAME,ASSEMBLYDLL,CLASSNAME) 
VALUES(6,'SBO','SBO Stock Transfers','SCExpertConnectSBOPlugin.dll','SCExpertConnectSBOPlugin.StockTransfer')

-- *** Work Orders *** --
INSERT INTO SCEXPERTCONNECTPLUGINTYPES(PLUGINTYPEID,PLUGINTYPE,PLUGINNAME,ASSEMBLYDLL,CLASSNAME) 
VALUES(7,'SBO','SBO Work Orders','SCExpertConnectSBOPlugin.dll','SCExpertConnectSBOPlugin.WorkOrders')

-- *** Production Orders *** --
INSERT INTO SCEXPERTCONNECTPLUGINTYPES(PLUGINTYPEID,PLUGINTYPE,PLUGINNAME,ASSEMBLYDLL,CLASSNAME) 
VALUES(8,'SBO','SBO Production Orders','SCExpertConnectSBOPlugin.dll','SCExpertConnectSBOPlugin.ProductionOrders')

-------- *** Drafts *** --
------INSERT INTO SCEXPERTCONNECTPLUGINTYPES(PLUGINTYPEID,PLUGINTYPE,PLUGINNAME,ASSEMBLYDLL,CLASSNAME) 
------VALUES(9,'SBO','SBO Drafts','SCExpertConnectSBOPlugin.dll','SCExpertConnectSBOPlugin.Drafts')

-- *** Product Trees *** --
INSERT INTO SCEXPERTCONNECTPLUGINTYPES(PLUGINTYPEID,PLUGINTYPE,PLUGINNAME,ASSEMBLYDLL,CLASSNAME) 
VALUES(10,'SBO','SBO Product Trees','SCExpertConnectSBOPlugin.dll','SCExpertConnectSBOPlugin.ProductTree')

-- *** Inventory Adjustments *** --
INSERT INTO SCEXPERTCONNECTPLUGINTYPES(PLUGINTYPEID,PLUGINTYPE,PLUGINNAME,ASSEMBLYDLL,CLASSNAME) 
VALUES(11,'SBO','SBO General Entry/Exit','SCExpertConnectSBOPlugin.dll','SCExpertConnectSBOPlugin.InventoryAdjustments')

-- *** Inventory status changes *** --
INSERT INTO SCEXPERTCONNECTPLUGINTYPES(PLUGINTYPEID,PLUGINTYPE,PLUGINNAME,ASSEMBLYDLL,CLASSNAME) 
VALUES(12,'SBO','SBO Stock Transfers','SCExpertConnectSBOPlugin.dll','SCExpertConnectSBOPlugin.InventoryStatusChange')

---------------------------------------- 
-- Document Types (ObjType Parameter) --
----------------------------------------
--13  - Invoices
--14  - CreditNotes
--15  - DeliveryNotes
--16  - Returns
--17  - Orders
--18  - PurchaseInvoices
--19  - PurchaseCreditNotes
--20  - PurchaseDeliveryNotes
--21  - PurchaseReturns
--22  - PurchaseOrders
--23  - Quotations
--59  - Inventory General Entry
--60  - Inventory General Exit
--112 - Drafts
--------------------------

--------------------
-- Plugin Instances
--------------------

-- *** Items *** --
INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
VALUES(3,'SBO Items Import',3,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'SKU','C:\SCExpertConnectFiles\XSLMaps\SBOItemsToExpert.xslt','SCEXPERT',1)

-- Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(3,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(3,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(3,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(3,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(3,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(3,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(3,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(3,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(3,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(3,'DBType','MSSQL2005')			

-- *** Product Trees *** --
INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
VALUES(13,'SBO Product Trees Import',10,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'SKU','C:\SCExpertConnectFiles\XSLMaps\SBOProductTreesToExpert.xslt','SCEXPERT',1)

-- Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(13,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(13,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(13,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(13,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(13,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(13,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(13,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(13,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(13,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(13,'DBType','MSSQL2005')			

-- *** Cards *** --
INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
VALUES(4,'SBO Company Import',4,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'COMPANY','C:\SCExpertConnectFiles\XSLMaps\SBOCardsToExpert.xslt','SCEXPERT',1)

-- Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(4,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(4,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(4,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(4,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(4,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(4,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(4,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(4,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(4,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(4,'DBType','MSSQL2005')			

-- *** Purchase Orders *** --
INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,EXPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
VALUES(5,'SBO Purchase Orders',5,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'INBOUND','C:\SCExpertConnectFiles\XSLMaps\SBOPOToExpert.xslt','C:\SCExpertConnectFiles\XSLMaps\ReceiptToSBODocument.xslt','SCEXPERT',1)

-- Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'DBType','MSSQL2005')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'DocumentObjType','22')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'DocumentStatus','Open')    -- Valid values: Open / Close / *			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'DocumentDaysRange','1000')			
-- Export Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'ExportTempFilePath','C:\SCExpertConnectFiles\ExportTempFiles\')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'SaveTempFile','1')			
-- Close Base Document - indicates whether the base document will be closed when creating the target document
-- Valid values: 0 - Do not close - this is the recomended settings - DI will handle this itself.
--				 1 - Close only if the target document was created succesfully
--				 2 - Always close
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'CloseBaseDoc','0')			
-- Attributes to be copied from base doc to target doc. list seperated by ";" (semicolon)
-- If the attribute is UDF -> should be the constant UDF_ + AtName
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'CopyTargetDocAttributeList','')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(5,'AddRemainQtyLines','0')			

-- *** Sales Orders *** --
INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,EXPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
VALUES(6,'SBO Sales Orders',5,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'OUTBOUND','C:\SCExpertConnectFiles\XSLMaps\SBOSOToExpert.xslt','C:\SCExpertConnectFiles\XSLMaps\OutboundOrderToSBODocument.xslt','SCEXPERT',1)

-- Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'DBType','MSSQL2005')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'DocumentObjType','17')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'DocumentStatus','Open')    -- Valid values: Open / Close / *			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'DocumentDaysRange','1000')			
-- Export Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'ExportTempFilePath','C:\SCExpertConnectFiles\ExportTempFiles\')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'SaveTempFile','1')			
-- Close Base Document - indicates whether the base document will be closed when creating the target document
-- Valid values: 0 - Do not close - this is the recomended settings - DI will handle this itself.
--				 1 - Close only if the target document was created succesfully
--				 2 - Always close
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'CloseBaseDoc','0')			
-- Attributes to be copied from base doc to target doc. list seperated by ";" (semicolon)
-- If the attribute is UDF -> should be the constant UDF_ + AtName
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'CopyTargetDocAttributeList','')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(6,'AddRemainQtyLines','0')			


-- *** Stock Transfers *** --
-- 2 Plugins are initiated when getting this transaction - one to map inbound order and one for the outbound.

INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
VALUES(7,'SBO Stock Transfers (Outbound)',6,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'OUTBOUND','C:\SCExpertConnectFiles\XSLMaps\SBOStockTransferToExpertOO.xslt','SCEXPERT',1)

-- Outboubnd Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(7,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(7,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(7,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(7,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(7,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(7,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(7,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(7,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(7,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(7,'DBType','MSSQL2005')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(7,'DocumentDaysRange','1000')			


INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
VALUES(8,'SBO Stock Transfers (Inbound)',6,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'INBOUND','C:\SCExpertConnectFiles\XSLMaps\SBOStockTransferToExpertIO.xslt','SCEXPERT',1)

-- Inboubnd Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(8,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(8,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(8,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(8,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(8,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(8,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(8,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(8,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(8,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(8,'DBType','MSSQL2005')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(8,'DocumentDaysRange','1000')			


-------- *** Work Orders *** --
-------- 2 Plugins are initiated when getting this transaction - one to map inbound order and one for the outbound.

------INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,TRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
------VALUES(9,'SBO Work Orders (Outbound)',7,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'OUTBOUND','C:\SCExpertConnectFiles\XSLMaps\SBOStockTransferToExpertOO.xslt','SCEXPERT',1)

-------- Outboubnd Params
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'Company','SBODemoUS')			
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'Server','127.0.0.1')
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'UserName','manager')					
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'Password','manager')				
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'TrustedConnection','0')
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'DBUserName','m4n')
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'DBPassword','m4n')
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'Language','3')	
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'Active','1')	
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'DBType','MSSQL2005')			
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'DocumentDaysRange','1000')			
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'DocumentStatus','Instruction')    -- Valid values: New / Instruction / Complete / *			


------INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,TRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
------VALUES(10,'SBO Work Orders (Inbound)',7,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'INBOUND','C:\SCExpertConnectFiles\XSLMaps\SBOProductionOrderToExpertIO.xslt','SCEXPERT',1)

-------- Inboubnd Params
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(10,'Company','SBODemoUS')			
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(10,'Server','127.0.0.1')
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(10,'UserName','manager')					
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(10,'Password','manager')				
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(10,'TrustedConnection','0')
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(10,'DBUserName','m4n')
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(10,'DBPassword','m4n')
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(10,'Language','3')	
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(10,'Active','1')	
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(10,'DBType','MSSQL2005')			
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(10,'DocumentDaysRange','1000')			
------INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(9,'DocumentStatus','Instruction')    -- Valid values: New / Instruction / Complete / *			


-- *** Production Orders *** --
-- 2 Plugins are initiated when getting this transaction - one to map inbound order and one for the outbound.

INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
VALUES(11,'SBO Production Orders (Inbound)',8,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'INBOUND','C:\SCExpertConnectFiles\XSLMaps\SBOProductionOrderToExpertIO.xslt','SCEXPERT',1)

-- Inboubnd Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'DBType','MSSQL2005')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'DocumentDaysRange','1000')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(11,'DocumentStatus','Released')    -- Valid values: Released / Planned / *			


INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
VALUES(12,'SBO Production Orders (Outbound)',8,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'OUTBOUND','C:\SCExpertConnectFiles\XSLMaps\SBOProductionOrderToExpertOO.xslt','SCEXPERT',1)

-- Outboubnd Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'DBType','MSSQL2005')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'DocumentDaysRange','1000')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(12,'DocumentStatus','Released')    -- Valid values: Released / Planned / *			


-- *** Drafts *** --
INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
VALUES(14 ,'SBO Drafts',9,'IMPORT','C:\SCExpertConnectFiles\Logs\',1,'OUTBOUND','C:\SCExpertConnectFiles\XSLMaps\SBODraftsToExpertOO.xslt','SCEXPERT',1)

-- Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'Server','.')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'DBType','MSSQL2005')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'DocumentObjType','17')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'DocumentStatus','Open')    -- Valid values: Open / Close / *			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(14,'DocumentDaysRange','1000')			


-- *** Inventory General Entry *** --
INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,EXPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE,EXPORTTRANSACTIONCONTENTFILTER) 
VALUES(15,'SBO General Entry',11,'EXPORT','C:\SCExpertConnectFiles\Logs\',1,'INVADJ','','C:\SCExpertConnectFiles\XSLMaps\InvAdjToSBOGenEntry.xslt','SCEXPERT',1,'DATACOLLECTION/DATA/ACTIVITYTYPE,SUBQTY')

-- Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'DBType','MSSQL2005')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'ExportTempFilePath','C:\SCExpertConnectFiles\ExportTempFiles\')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(15,'SaveTempFile','0')			


-- *** Inventory General Exit *** --
INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,EXPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE,EXPORTTRANSACTIONCONTENTFILTER) 
VALUES(16,'SBO General Exit',11,'EXPORT','C:\SCExpertConnectFiles\Logs\',1,'INVADJ','','C:\SCExpertConnectFiles\XSLMaps\InvAdjToSBOGenExit.xslt','SCEXPERT',1,'DATACOLLECTION/DATA/ACTIVITYTYPE,ADDQTY')

-- Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'DBType','MSSQL2005')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'ExportTempFilePath','C:\SCExpertConnectFiles\ExportTempFiles\')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(16,'SaveTempFile','0')			



-- *** Inventory Inventory status changed *** --
INSERT INTO SCEXPERTCONNECTPLUGINS(PLUGINID,PLUGINDESCRIPTION,PLUGINTYPEID,PLUGINTRANSACTIONTYPE,LOGPATH,LOGLEVEL,BOTYPE,IMPORTTRANSLATIONFILE,EXPORTTRANSLATIONFILE,WAREHOUSEID,COMMITBOONBOELEMENTFAILURE) 
VALUES(17,'SBO Stock transfers',12,'EXPORT','C:\SCExpertConnectFiles\Logs\',1,'INVADJ','','C:\SCExpertConnectFiles\XSLMaps\InvStatusChangeToSBOStockTransfer.xslt','SCEXPERT',1)

-- Params
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'Company','SBODemoUS')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'Server','127.0.0.1')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'UserName','manager')					
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'Password','manager')				
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'TrustedConnection','0')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'DBUserName','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'DBPassword','m4n')
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'Language','3')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'Active','1')	
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'DBType','MSSQL2005')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'ExportTempFilePath','C:\SCExpertConnectFiles\ExportTempFiles\')			
INSERT INTO SCEXPERTCONNECTPLUGINPARAMS(PLUGINID,PARAMNAME,PARAMVALUE) VALUES(17,'SaveTempFile','0')			


--************************************************
-- Events Registration (For export interfaces)
--************************************************
---- snapshot
--INSERT INTO SCEXPERTPLUGINEVENTREGISTRATION(PLUGINID,EVENTID,WAREHOUSEID,CONSIGNEE) VALUES(11,36,'SCEXPERT','')  
-- receipt close
INSERT INTO SCEXPERTPLUGINEVENTREGISTRATION(PLUGINID,EVENTID,WAREHOUSEID,CONSIGNEE) VALUES(5,40,'SCEXPERT','')  
-- outbound order shipped
INSERT INTO SCEXPERTPLUGINEVENTREGISTRATION(PLUGINID,EVENTID,WAREHOUSEID,CONSIGNEE) VALUES(6,21,'SCEXPERT','')  
---- outbound order loaded
--INSERT INTO SCEXPERTPLUGINEVENTREGISTRATION(PLUGINID,EVENTID,WAREHOUSEID,CONSIGNEE) VALUES(14,281,'SCEXPERT','') 
---- outbound order planned
--INSERT INTO SCEXPERTPLUGINEVENTREGISTRATION(PLUGINID,EVENTID,WAREHOUSEID,CONSIGNEE) VALUES(15,20,'SCEXPERT','')  
-- Inventory Adjustments - Add qty
INSERT INTO SCEXPERTPLUGINEVENTREGISTRATION(PLUGINID,EVENTID,WAREHOUSEID,CONSIGNEE) VALUES(15,31,'SCEXPERT','')  
-- Inventory Adjustments - Sub qty
INSERT INTO SCEXPERTPLUGINEVENTREGISTRATION(PLUGINID,EVENTID,WAREHOUSEID,CONSIGNEE) VALUES(16,31,'SCEXPERT','')  
-- Inventory status changed
INSERT INTO SCEXPERTPLUGINEVENTREGISTRATION(PLUGINID,EVENTID,WAREHOUSEID,CONSIGNEE) VALUES(17,30,'SCEXPERT','')  













-- ******************* Missing functionality *******************

--   General issues:
-------------------------
--1)	Should we build a plugin for synchronizing the initial data? (cards,Items,Inventory)
--2)	Getting consignees according to wh code received from SBO. (getConsigneeForCompany)
--3)    Create Recipt / Plan order.
--4)	Batch numbers and serials.
--5)    Blind receiving.
--6)	Expert Work orders mapping.



--<SerialNumbers>
--  <row>
--  <InternalSerialNumber>ST-005</InternalSerialNumber>
-- <BaseLineNumber>0</BaseLineNumber>
--  </row>
--  <row>
--  <InternalSerialNumber>ST-006</InternalSerialNumber> 
-- <BaseLineNumber>1</BaseLineNumber>
--  </row>
--  </SerialNumbers>