Create View repCompanyByConsignee
AS
SELECT 
COM.COMPANY,
COM.COMPANYNAME,
COM.COMPANYTYPE,
COM.OTHERCOMPANY,
COM.COMPANYGROUP,
CONT.STREET1,
CONT.CITY,
CONT.STATE,
CONT.ZIP,
COM.CONSIGNEE 
FROM COMPANY COM INNER JOIN CONTACT CONT ON COM.CONTACTID = CONT.CONTACTID