CREATE VIEW dbo.repFlowthrowghDelNote
AS
SELECT     dbo.FLOWTHROUGHHEADER.CONSIGNEE, dbo.FLOWTHROUGHHEADER.FLOWTHROUGH, dbo.FLOWTHROUGHHEADER.ORDERTYPE, 
                      dbo.FLOWTHROUGHHEADER.REFERENCEORD, dbo.FLOWTHROUGHHEADER.SOURCECOMPANY, 
                      dbo.FLOWTHROUGHHEADER.SOURCECOMPANYTYPE, dbo.FLOWTHROUGHHEADER.TARGETCOMPANY, 
                      dbo.FLOWTHROUGHHEADER.TARGETCOMPANYTYPE, dbo.FLOWTHROUGHHEADER.STATUS, dbo.FLOWTHROUGHHEADER.STATUSDATE, 
                      dbo.FLOWTHROUGHHEADER.NOTES, dbo.FLOWTHROUGHHEADER.CREATEDATE, dbo.FLOWTHROUGHHEADER.SCHEDULEDARRIVALDATE, 
                      dbo.FLOWTHROUGHHEADER.REQUESTEDDELIVERYDATE, dbo.FLOWTHROUGHHEADER.SCHEDULEDDELIVERYDATE, 
                      dbo.FLOWTHROUGHHEADER.SHIPPEDDATE, dbo.FLOWTHROUGHHEADER.STAGINGLANE, dbo.FLOWTHROUGHHEADER.SHIPMENT, 
                      dbo.FLOWTHROUGHHEADER.STOPNUMBER, dbo.FLOWTHROUGHHEADER.LOADINGSEQ, dbo.FLOWTHROUGHHEADER.ROUTINGSET, 
                      dbo.FLOWTHROUGHHEADER.ROUTE, dbo.FLOWTHROUGHHEADER.DELIVERYSTATUS, dbo.FLOWTHROUGHHEADER.POD, 
                      dbo.FLOWTHROUGHHEADER.ORDERPRIORITY, dbo.FLOWTHROUGHDETAIL.FLOWTHROUGHLINE, dbo.FLOWTHROUGHDETAIL.SKU, 
                      dbo.FLOWTHROUGHDETAIL.QTYORIGINAL, dbo.FLOWTHROUGHDETAIL.QTYRECEIVED, dbo.FLOWTHROUGHDETAIL.QTYMODIFIED, 
                      dbo.SKU.SKUDESC, COMPANY_1.COMPANYNAME AS TARGETCOMPANYNAME, dbo.COMPANY.COMPANYNAME AS SOURCECOMPANYNAME, 
                      dbo.CONSIGNEE.CONSIGNEENAME, dbo.CONTACT.STREET1 AS TSTREET1, dbo.CONTACT.CITY AS TCITY, dbo.CONTACT.ZIP AS TZIP, 
                      dbo.CONTACT.CONTACT1NAME AS TCONTACT1NAME, dbo.CONTACT.CONTACT1PHONE AS TCONTACT1PHONE, CONTACT_1.STREET1 AS SSTREET1, 
                      CONTACT_1.CITY AS SCITY, CONTACT_1.ZIP AS SZIP, CONTACT_1.CONTACT1NAME AS SCONTACT1NAME, 
                      CONTACT_1.CONTACT1PHONE AS CONTACT1PHONE
FROM         dbo.FLOWTHROUGHHEADER INNER JOIN
                      dbo.FLOWTHROUGHDETAIL ON dbo.FLOWTHROUGHHEADER.CONSIGNEE = dbo.FLOWTHROUGHDETAIL.CONSIGNEE AND 
                      dbo.FLOWTHROUGHHEADER.FLOWTHROUGH = dbo.FLOWTHROUGHDETAIL.FLOWTHROUGH INNER JOIN
                      dbo.SKU ON dbo.FLOWTHROUGHHEADER.CONSIGNEE = dbo.SKU.CONSIGNEE AND dbo.FLOWTHROUGHDETAIL.SKU = dbo.SKU.SKU INNER JOIN
                      dbo.COMPANY ON dbo.FLOWTHROUGHHEADER.CONSIGNEE = dbo.COMPANY.CONSIGNEE AND 
                      dbo.FLOWTHROUGHHEADER.SOURCECOMPANY = dbo.COMPANY.COMPANY AND 
                      dbo.FLOWTHROUGHHEADER.SOURCECOMPANYTYPE = dbo.COMPANY.COMPANYTYPE INNER JOIN
                      dbo.COMPANY COMPANY_1 ON dbo.FLOWTHROUGHHEADER.CONSIGNEE = COMPANY_1.CONSIGNEE AND 
                      dbo.FLOWTHROUGHHEADER.TARGETCOMPANY = COMPANY_1.COMPANY AND 
                      dbo.FLOWTHROUGHHEADER.TARGETCOMPANYTYPE = COMPANY_1.COMPANYTYPE INNER JOIN
                      dbo.CONSIGNEE ON dbo.FLOWTHROUGHHEADER.CONSIGNEE = dbo.CONSIGNEE.CONSIGNEE INNER JOIN
                      dbo.CONTACT ON COMPANY_1.CONTACTID = dbo.CONTACT.CONTACTID INNER JOIN
                      dbo.CONTACT CONTACT_1 ON dbo.COMPANY.CONTACTID = CONTACT_1.CONTACTID

