IF OBJECT_ID('repInvOnHold') IS NOT NULL
DROP VIEW repInvOnHold
GO

CREATE VIEW [dbo].[repInvOnHold]
AS
SELECT     INV.LOADID, INV.STATUS, STT.DESCRIPTION AS STATUSDESC, INV.ACTIVITYSTATUS, CDD.DESCRIPTION AS ACTIVITYSTATUSDESC, INV.LOCATION, 
                      INV.CONSIGNEE, CON.CONSIGNEENAME, INV.SKU, dbo.SKU.SKUDESC, INV.RECEIPT, INV.RECEIPTLINE, INV.UNITS, INV.WAREHOUSEAREA
FROM         dbo.INVLOAD AS INV INNER JOIN
                      dbo.INVSTATUSES AS STT ON INV.STATUS = STT.CODE INNER JOIN
                      dbo.SKU ON INV.CONSIGNEE = dbo.SKU.CONSIGNEE AND INV.SKU = dbo.SKU.SKU LEFT OUTER JOIN
                      dbo.SKUCLS AS CLS ON dbo.SKU.CLASSNAME = CLS.CLASSNAME INNER JOIN
                      dbo.CONSIGNEE AS CON ON INV.CONSIGNEE = CON.CONSIGNEE LEFT OUTER JOIN
                      dbo.CODELISTDETAIL AS CDD ON INV.ACTIVITYSTATUS = CDD.CODE
WHERE     (INV.STATUS <> 'AVAILABLE') AND (INV.STATUS <> '') AND (INV.STATUS IS NOT NULL) AND 
                      (CDD.CODELISTCODE = 'ACTIVSTT' OR
                      CDD.CODELISTCODE IS NULL)
