Create View repInvByStatus
AS
SELECT 
INV.STATUS, 
STT.DESCRIPTION AS STATUSDESC, 
SKU.SKUGROUP, 
SKU.CLASSNAME AS SKUCLASS, 
CLS.CLASSDESCRIPTION AS SKUCLASSDESC, 
INV.CONSIGNEE, 
CON.CONSIGNEENAME,
INV.SKU, 
SKU.SKUDESC, 
SUM(INV.UNITS) AS UNITS, 
SUM(INV.UNITSALLOCATED) AS UNITSALLOCATED, 
SUM(INV.UNITSINPROCESS) AS UNITSINPROCESS, 
SUM(INV.UNITSPICKED) AS UNITSPICKED
FROM INVLOAD INV JOIN INVSTATUSES STT ON INV.STATUS = STT.CODE JOIN SKU ON INV.CONSIGNEE = SKU.CONSIGNEE AND INV.SKU = SKU.SKU
LEFT OUTER JOIN SKUCLS CLS ON SKU.CLASSNAME = CLS.CLASSNAME JOIN CONSIGNEE CON ON INV.CONSIGNEE = CON.CONSIGNEE
GROUP BY INV.STATUS, STT.DESCRIPTION, SKU.SKUGROUP, SKU.CLASSNAME, CLS.CLASSDESCRIPTION, INV.CONSIGNEE, CON.CONSIGNEENAME,
INV.SKU, SKU.SKUDESC