Create View repLoadByStatus
AS
SELECT 
AUDIT.ACTIVITYDATE,
AUDIT.CONSIGNEE ,
AUDIT.SKU ,
AUDIT.FROMLOAD ,
AUDIT.TOLOAD ,
INS.DESCRIPTION AS FROMSTATUS,
INS2.DESCRIPTION AS TOSTATUS,
AUDIT.ADDUSER,SKU.SKUDESC
FROM AUDIT INNER JOIN SKU ON AUDIT.SKU = SKU.SKU INNER JOIN INVSTATUSES INS ON AUDIT.FROMSTATUS = INS.CODE INNER JOIN INVSTATUSES INS2 ON AUDIT.TOSTATUS = INS2.CODE
WHERE audit.activitytype='SETSTATUS'