
ALTER VIEW [dbo].[repLoadingDiagram]
AS
 /* --- Author: Ravi -- Description: Added the ISNULL condition for the SIDE column 12/11/2015 */
 /* --- Added 'driver' -- RJM 12/12/15  --- */
SELECT DISTINCT sh.SHIPMENT  
 ,sh.DOOR  
 ,sh.TRAILER  
 ,sh.DRIVER1
 --,sc.VEHICLELOCATION  
 ,(CASE WHEN len(sc.VEHICLELOCATION)=2 THEN '0'+sc.VEHICLELOCATION ELSE sc.VEHICLELOCATION END) as VEHICLELOCATION
 ,sc.HANDLINGUNIT  
 ,cm.COMPANYNAME  
-- ,isnull(vl.SIDE, 'L') AS SIDE  
 ,ISNULL((CASE WHEN len(vl.SIDE)=2 THEN '0'+vl.SIDE ELSE vl.SIDE END),'L') as SIDE
 ,(  
  SELECT count(DISTINCT SHIPTO)  
  FROM SHIPMENTDETAIL  
  INNER JOIN OUTBOUNDORHEADER ON SHIPMENTDETAIL.CONSIGNEE = OUTBOUNDORHEADER.CONSIGNEE  
   AND SHIPMENTDETAIL.ORDERID = OUTBOUNDORHEADER.ORDERID  
  WHERE SHIPMENTDETAIL.SHIPMENT = sh.SHIPMENT  
  ) AS totalstops  
 ,(  
  SELECT count(DISTINCT HANDLINGUNIT)  
  FROM SHIPMENTCOMPARTMENT  
  WHERE SHIPMENTCOMPARTMENT.SHIPMENT = sh.SHIPMENT  
  ) AS totalcontainers  
 ,od.STOPNUMBER AS STOP  
FROM SHIPMENT sh  
LEFT JOIN SHIPMENTCOMPARTMENT sc ON sh.SHIPMENT = sc.SHIPMENT  
LEFT JOIN LOADS lo ON sc.HANDLINGUNIT = lo.HANDLINGUNIT  
 OR sc.HANDLINGUNIT = lo.LOADID  
INNER JOIN ORDERLOADS ol ON lo.LOADID = ol.LOADID  
 AND ol.DOCUMENTTYPE = 'OUTBOUND'  
LEFT JOIN OUTBOUNDORHEADER oh ON ol.ORDERID = oh.ORDERID  
 AND ol.CONSIGNEE = oh.CONSIGNEE  
LEFT JOIN COMPANY cm ON oh.COMPANYTYPE = cm.COMPANYTYPE  
 AND oh.CONSIGNEE = cm.CONSIGNEE  
 AND oh.TARGETCOMPANY = cm.COMPANY  
--left outer join vehicle vh on sh.VEHICLE=vh.VEHICLEID  
LEFT JOIN VEHICLELOCATIONS vl  
 --on vh.VEHICLETYPENAME=vl.VEHICLETYPE   
-- ON sc.VEHICLELOCATION = vl.LOCATION  
ON  (CASE WHEN len(sc.VEHICLELOCATION)=2 THEN '0'+sc.VEHICLELOCATION ELSE sc.VEHICLELOCATION END)  = vl.LOCATION
LEFT JOIN SHIPMENTDETAIL sd ON sh.SHIPMENT = sd.SHIPMENT  
 AND oh.ORDERID = sd.ORDERID  
 AND ol.ORDERLINE = sd.ORDERLINE  
LEFT JOIN OUTBOUNDORDETAIL od ON sh.SHIPMENT = sd.SHIPMENT  
 AND oh.ORDERID = od.ORDERID  
 AND ol.ORDERLINE = od.ORDERLINE 
 
UNION ALL

SELECT DISTINCT sh.SHIPMENT
	,sh.DOOR
	,sh.TRAILER
	,sh.DRIVER1
	,sc.VEHICLELOCATION
	,sc.HANDLINGUNIT
	,cm.COMPANYNAME
	--isnull(vl.SIDE, 'L') AS SIDE
	,ISNULL((CASE WHEN len(vl.SIDE)=2 THEN '0'+vl.SIDE ELSE vl.SIDE END),'L')
	,(
		SELECT count(DISTINCT SHIPTO)
		FROM SHIPMENTDETAIL
		INNER JOIN FLOWTHROUGHHEADER ON SHIPMENTDETAIL.CONSIGNEE = FLOWTHROUGHHEADER.CONSIGNEE
			AND SHIPMENTDETAIL.ORDERID = FLOWTHROUGHHEADER.FLOWTHROUGH
		WHERE SHIPMENTDETAIL.SHIPMENT = sh.SHIPMENT
		) AS totalstops
	,(
		SELECT count(DISTINCT HANDLINGUNIT)
		FROM SHIPMENTCOMPARTMENT
		WHERE SHIPMENTCOMPARTMENT.SHIPMENT = sh.SHIPMENT
		) AS totalcontainers
	,fd.STOPNUMBER AS STOP
FROM SHIPMENT sh
LEFT JOIN SHIPMENTCOMPARTMENT sc ON sh.SHIPMENT = sc.SHIPMENT
LEFT JOIN LOADS lo ON sc.HANDLINGUNIT = lo.LOADID
INNER JOIN ORDERLOADS ol ON lo.LOADID = ol.LOADID
	AND ol.DOCUMENTTYPE = 'FLWTH'
LEFT JOIN FLOWTHROUGHHEADER fw ON ol.ORDERID = fw.FLOWTHROUGH
	AND ol.CONSIGNEE = fw.CONSIGNEE
LEFT JOIN COMPANY cm ON fw.TARGETCOMPANYTYPE = cm.COMPANYTYPE
	AND FW.CONSIGNEE = cm.CONSIGNEE
	AND fw.TARGETCOMPANY = cm.COMPANY
--left outer join vehicle vh on sh.VEHICLE=vh.VEHICLEID
LEFT JOIN VEHICLELOCATIONS vl
	--on vh.VEHICLETYPENAME=vl.VEHICLETYPE 
	ON sc.VEHICLELOCATION = vl.LOCATION
LEFT JOIN SHIPMENTDETAIL sd ON sh.SHIPMENT = sd.SHIPMENT
	AND fw.FLOWTHROUGH = sd.ORDERID
	AND ol.ORDERLINE = sd.ORDERLINE
LEFT JOIN FLOWTHROUGHDETAIL fd ON sh.SHIPMENT = sd.SHIPMENT
	AND fw.FLOWTHROUGH = fd.FLOWTHROUGH
	AND ol.ORDERLINE = fd.FLOWTHROUGHLINE


GO


