CREATE VIEW dbo.repOutboundDelNote
AS
SELECT     dbo.OUTBOUNDORHEADER.CONSIGNEE, dbo.OUTBOUNDORHEADER.ORDERID, dbo.OUTBOUNDORHEADER.ORDERTYPE, 
                      dbo.OUTBOUNDORHEADER.REFERENCEORD, dbo.OUTBOUNDORHEADER.TARGETCOMPANY, dbo.OUTBOUNDORHEADER.COMPANYTYPE, 
                      dbo.OUTBOUNDORHEADER.STATUS, dbo.OUTBOUNDORHEADER.CREATEDATE, dbo.OUTBOUNDORHEADER.NOTES, 
                      dbo.OUTBOUNDORHEADER.STAGINGLANE, dbo.OUTBOUNDORHEADER.REQUESTEDDATE, dbo.OUTBOUNDORHEADER.SCHEDULEDDATE, 
                      dbo.OUTBOUNDORHEADER.SHIPPEDDATE, dbo.OUTBOUNDORHEADER.SHIPMENT, dbo.OUTBOUNDORHEADER.STOPNUMBER, 
                      dbo.OUTBOUNDORHEADER.WAVE, dbo.OUTBOUNDORHEADER.STATUSDATE, dbo.OUTBOUNDORHEADER.LOADINGSEQ, 
                      dbo.OUTBOUNDORHEADER.ROUTINGSET, dbo.OUTBOUNDORHEADER.ROUTE, dbo.OUTBOUNDORHEADER.DELIVERYSTATUS, 
                      dbo.OUTBOUNDORHEADER.POD, dbo.OUTBOUNDORHEADER.ORDERPRIORITY, dbo.OUTBOUNDORHEADER.HOSTORDERID, 
                      dbo.OUTBOUNDORHEADER.SHIPTO, dbo.OUTBOUNDORHEADER.EXPECTEDDATE, dbo.OUTBOUNDORDETAIL.ORDERLINE, 
                      dbo.OUTBOUNDORDETAIL.REFERENCEORDLINE, dbo.OUTBOUNDORDETAIL.SKU, dbo.OUTBOUNDORDETAIL.INVENTORYSTATUS, 
                      dbo.OUTBOUNDORDETAIL.QTYORIGINAL, dbo.OUTBOUNDORDETAIL.QTYMODIFIED, dbo.OUTBOUNDORDETAIL.QTYALLOCATED, 
                      dbo.OUTBOUNDORDETAIL.QTYPICKED, dbo.OUTBOUNDORDETAIL.QTYSTAGED, dbo.OUTBOUNDORDETAIL.QTYLOADED, 
                      dbo.OUTBOUNDORDETAIL.QTYSHIPPED, dbo.OUTBOUNDORDETAIL.EXPLOADEDFLAG, dbo.OUTBOUNDORDETAIL.LINEOUM, 
                      dbo.OUTBOUNDORDETAIL.UOMQTY, dbo.COMPANY.COMPANYNAME, dbo.CONSIGNEE.CONSIGNEENAME, dbo.SKU.SKUDESC, 
                      dbo.CONTACT.STREET1, dbo.CONTACT.CITY, dbo.CONTACT.STATE, dbo.CONTACT.ZIP, dbo.CONTACT.CONTACT1NAME, 
                      dbo.CONTACT.CONTACT1PHONE
FROM         dbo.OUTBOUNDORHEADER INNER JOIN
                      dbo.OUTBOUNDORDETAIL ON dbo.OUTBOUNDORHEADER.CONSIGNEE = dbo.OUTBOUNDORDETAIL.CONSIGNEE AND 
                      dbo.OUTBOUNDORHEADER.ORDERID = dbo.OUTBOUNDORDETAIL.ORDERID INNER JOIN
                      dbo.COMPANY ON dbo.OUTBOUNDORHEADER.CONSIGNEE = dbo.COMPANY.CONSIGNEE AND 
                      dbo.OUTBOUNDORHEADER.COMPANYTYPE = dbo.COMPANY.COMPANYTYPE AND 
                      dbo.OUTBOUNDORHEADER.TARGETCOMPANY = dbo.COMPANY.COMPANY INNER JOIN
                      dbo.CONSIGNEE ON dbo.OUTBOUNDORHEADER.CONSIGNEE = dbo.CONSIGNEE.CONSIGNEE INNER JOIN
                      dbo.SKU ON dbo.OUTBOUNDORHEADER.CONSIGNEE = dbo.SKU.CONSIGNEE AND dbo.OUTBOUNDORDETAIL.SKU = dbo.SKU.SKU INNER JOIN
                      dbo.CONTACT ON dbo.COMPANY.CONTACTID = dbo.CONTACT.CONTACTID

