Create View repPickLoc
as
SELECT 
PL.CONSIGNEE,
PL.SKU,
SKU.SKUDESC,
PL.LOCATION,
LOCATION.PICKREGION,
PL.CURRENTQTY,
PL.PENDINGQTY,
PL.ALLOCATEDQTY,
PL.NORMALREPLQTY,
PL.REPLQTY,
PL.MAXIMUMQTY,
PL.OVERALLOCATEDQTY
FROM PICKLOC PL INNER JOIN SKU ON SKU.SKU = PL.SKU AND PL.CONSIGNEE = SKU.CONSIGNEE INNER JOIN LOCATION ON LOCATION.LOCATION = PL.LOCATION