Create View repPickingPlanShort
AS
SELECT 
OD.CONSIGNEE, 
OD.ORDERID, 
OD.ORDERLINE, 
OD.REFERENCEORDLINE, 
OD.SKU, 
SK.SKUDESC, 
OD.INVENTORYSTATUS, 
INVSTAT.DESCRIPTION AS INVSTATDESC,
OD.QTYORIGINAL, 
OD.QTYMODIFIED, 
OD.QTYALLOCATED, 
OD.QTYPICKED, 
OD.QTYSTAGED, 
OD.QTYLOADED, 
OD.QTYSHIPPED
FROM OUTBOUNDORDETAIL OD JOIN SKU SK ON OD.CONSIGNEE = SK.CONSIGNEE AND OD.SKU = SK.SKU 
JOIN INVSTATUSES INVSTAT ON OD.INVENTORYSTATUS = INVSTAT.CODE JOIN OUTBOUNDORHEADER OH ON OD.CONSIGNEE = OH.CONSIGNEE AND OD.ORDERID = OH.ORDERID
WHERE (oh.STATUS = 'RELEASED' or oh.STATUS = 'PICKING') AND (od.QTYMODIFIED - od.QTYALLOCATED - od.QTYPICKED - od.QTYSTAGED - od.QTYLOADED - od.QTYSHIPPED) > 0

