Create View repPickByItem
AS
SELECT 
PD.PICKLIST, 
PD.PICKLISTLINE,
PH.WAVE, 
PD.ORDERID, 
PD.ORDERLINE, 
PD.CONSIGNEE, 
PD.SKU, 
PD.QTY, 
PD.ADJQTY, 
PD.PICKEDQTY, 
PD.FROMLOCATION, 
PD.FROMLOAD, 
PD.TOLOAD, 
PD.TOLOCATION,
SK.SKUDESC, 
OH.TARGETCOMPANY, 
OH.COMPANYTYPE, 
CM.COMPANYNAME
FROM PICKHEADER PH JOIN PICKDETAIL PD ON PH.PICKLIST=PD.PICKLIST JOIN SKU SK ON PD.CONSIGNEE = SK.CONSIGNEE AND PD.SKU = SK.SKU 
JOIN OUTBOUNDORHEADER OH ON PD.ORDERID = OH.ORDERID 
JOIN COMPANY CM ON OH.CONSIGNEE = CM.CONSIGNEE AND OH.TARGETCOMPANY = CM.COMPANY AND OH.COMPANYTYPE = CM.COMPANYTYPE
WHERE PD.STATUS = 'PLANNED' OR PD.STATUS='PARTPICKED'