Create View repProforma
AS
SELECT 
BILLINGCHARGESHEADER.CHARGEID, 
BILLINGCHARGESHEADER.BILLINGRUNID , 
BILLINGCHARGESHEADER.AGREEMENTNAME , 
BILLINGCHARGESHEADER.CONSIGNEE , 
BILLINGCHARGESHEADER.BILLFROMDATE , 
BILLINGCHARGESHEADER.BILLTODATE,
BILLINGCHARGESDETAIL.CHARGELINE ,
BILLINGCHARGESDETAIL.AGREEMENTLINE ,
'' AS TRANTYPE ,
'' AS BILLBASIS ,
BILLINGCHARGESDETAIL.UNITS ,
BILLINGCHARGESDETAIL.BILLTOTAL ,
BILLINGCHARGESDETAIL.CURRENCY , 
BILLINGCHARGESHEADER.ADDDATE , 
BILLINGCHARGESHEADER.ADDUSER
FROM BILLINGCHARGESHEADER INNER JOIN BILLINGCHARGESDETAIL ON BILLINGCHARGESHEADER.CHARGEID = BILLINGCHARGESDETAIL.CHARGEID