CREATE VIEW repRerShipSku
AS
SELECT DISTINCT 
INV.CONSIGNEE, 
INV.SKU, 
SKU.SKUDESC, 
ISNULL((SELECT SUM(IT.QTY) AS RETURNQTY 
	FROM INVENTORYTRANS IT INNER JOIN RECEIPTDETAIL RD ON RD.RECEIPT = IT.DOCUMENT AND RD.RECEIPTLINE = IT.LINE INNER JOIN INBOUNDORDDETAIL OD ON 
	OD.ORDERID = RD.ORDERID AND OD.ORDERLINE = RD.ORDERLINE JOIN INBOUNDORDHEADER OH ON OH.ORDERID = OD.ORDERID
	WHERE IT.INVTRNTYPE = 'CREATELOAD' AND IT.CONSIGNEE = INV.CONSIGNEE AND IT.SKU = INV.SKU AND OH.ORDERTYPE = 'RETURN'
	GROUP BY IT.CONSIGNEE, IT.SKU), 0) AS RETQTY,
ISNULL((SELECT SUM(ITOUT.QTY) AS SHIPQTY 
	FROM INVENTORYTRANS ITOUT 
        WHERE(ITOUT.CONSIGNEE = INV.CONSIGNEE AND ITOUT.SKU = INV.SKU) AND ITOUT.INVTRNTYPE = 'SHIPLOAD'
	GROUP BY ITOUT.CONSIGNEE, ITOUT.SKU ), 0) AS SHIPQTY 
FROM INVENTORYTRANS INV JOIN SKU ON INV.CONSIGNEE=SKU.CONSIGNEE AND INV.SKU=SKU.SKU  