Create View repReceivingDiscrepancies
as
SELECT 
RH.RECEIPT,
RH.STARTRECEIPTDATE,
RH.CARRIERCOMPANY,
RH.BOL,
RD.CONSIGNEE,
RD.SKU,
SK.SKUDESC,
RD.QTYEXPECTED,
RD.QTYRECEIVED,
RD.RECEIPTLINE 
FROM RECEIPTHEADER RH JOIN RECEIPTDETAIL RD ON RH.RECEIPT = RD.RECEIPT JOIN SKU SK ON RD.CONSIGNEE = SK.CONSIGNEE AND RD.SKU = SK.SKU 
WHERE QTYEXPECTED <> QTYRECEIVED