Create View repReceivingSummary
as
SELECT 
SKU.SKU,
SKU.CONSIGNEE,
SKU.SKUDESC,
SUM(AUDIT.TOQTY) AS RECEIVEDQTY 
FROM AUDIT JOIN SKU ON SKU.SKU = AUDIT.SKU AND SKU.CONSIGNEE = AUDIT.CONSIGNEE
JOIN RECEIPTHEADER ON AUDIT.DOCUMENT = RECEIPTHEADER.RECEIPT
GROUP BY SKU.SKU,SKU.CONSIGNEE,SKU.SKUDESC