Create View repShipBranch
AS
SELECT 
OH.CONSIGNEE,
OD.ORDERID,
OD.ORDERLINE,
OD.SKU,
SKU.SKUDESC,
SUM(OD.QTYSHIPPED)AS QTYSHIPPED,
CO.COMPANYNAME,
OH.SHIPPEDDATE AS ADDDATE 
FROM OUTBOUNDORHEADER OH INNER JOIN OUTBOUNDORDETAIL OD ON OD.CONSIGNEE=OH.CONSIGNEE AND OD.ORDERID = OH.ORDERID
INNER JOIN COMPANY CO ON CO.COMPANY = OH.TARGETCOMPANY AND CO.COMPANYTYPE = OH.COMPANYTYPE INNER JOIN SKU ON SKU.SKU = OD.SKU 
WHERE OH.STATUS ='SHIPPED' AND QTYSHIPPED > 0  
GROUP BY OH.CONSIGNEE,OD.ORDERID,OD.ORDERLINE,OD.SKU,SKU.SKUDESC,CO.COMPANYNAME,OH.SHIPPEDDATE