CREATE View repShipDetail
as
SELECT 
OD.ORDERLINE, 
OD.REFERENCEORDLINE, 
OD.SKU, 
OD.INVENTORYSTATUS, 
OD.QTYORIGINAL, 
OD.QTYMODIFIED, 
OD.QTYALLOCATED, 
OD.QTYPICKED, 
OD.QTYSTAGED, 
OD.QTYLOADED, 
OD.QTYSHIPPED, 
OD.EXPLOADEDFLAG, 
OD.LINEOUM, 
OD.UOMQTY,
OH.ORDERID,
OH.CONSIGNEE,
OH.ORDERTYPE,
OH.REFERENCEORD,
OH.TARGETCOMPANY,
OH.COMPANYTYPE,
OH.STATUS,
OH.CREATEDATE,
OH.NOTES,
OH.STAGINGLANE, 
OH.REQUESTEDDATE,
OH.SCHEDULEDDATE,
OH.SHIPPEDDATE,
OH.SHIPMENT,
OH.STOPNUMBER,
OH.WAVE,
OH.STATUSDATE,
OH.ADDDATE,
OH.ADDUSER,
OH.EDITDATE,
OH.EDITUSER,
COMP.COMPANYNAME,
CONS.CONSIGNEENAME,
SKU.SKUDESC 
FROM OUTBOUNDORHEADER OH JOIN OUTBOUNDORDETAIL OD ON OH.CONSIGNEE=OD.CONSIGNEE AND OH.ORDERID=OD.ORDERID
JOIN COMPANY COMP ON COMP.CONSIGNEE=OH.CONSIGNEE AND COMP.COMPANYTYPE=OH.COMPANYTYPE AND COMP.COMPANY=OH.TARGETCOMPANY
JOIN CONSIGNEE CONS ON CONS.CONSIGNEE=OH.CONSIGNEE JOIN SKU ON SKU.CONSIGNEE=OH.CONSIGNEE AND OD.SKU = SKU.SKU
WHERE OH.STATUS = 'SHIPPED'  AND OD.QTYSHIPPED > 0


