CREATE VIEW dbo.repTranshipmentDelNote
AS
SELECT     dbo.TRANSSHIPMENT.CONSIGNEE, dbo.TRANSSHIPMENT.TRANSSHIPMENT, dbo.TRANSSHIPMENT.ORDERTYPE, 
                      dbo.TRANSSHIPMENT.REFERENCEORD, dbo.TRANSSHIPMENT.SOURCECOMPANY, dbo.TRANSSHIPMENT.SOURCECOMPANYTYPE, 
                      dbo.TRANSSHIPMENT.TARGETCOMPANY, dbo.TRANSSHIPMENT.TARGETCOMPANYTYPE, dbo.TRANSSHIPMENT.STATUS, 
                      dbo.TRANSSHIPMENT.STATUSDATE, dbo.TRANSSHIPMENT.NOTES, dbo.TRANSSHIPMENT.CREATEDATE, 
                      dbo.TRANSSHIPMENT.SCHEDULEDARRIVALDATE, dbo.TRANSSHIPMENT.REQUESTEDDELIVERYDATE, 
                      dbo.TRANSSHIPMENT.SCHEDULEDDELIVERYDATE, dbo.TRANSSHIPMENT.SHIPPEDDATE, dbo.TRANSSHIPMENT.STAGINGLANE, 
                      dbo.TRANSSHIPMENT.SHIPMENT, dbo.TRANSSHIPMENT.STOPNUMBER, dbo.TRANSSHIPMENT.LOADINGSEQ, dbo.TRANSSHIPMENT.ROUTINGSET, 
                      dbo.TRANSSHIPMENT.ROUTE, dbo.TRANSSHIPMENT.DELIVERYSTATUS, dbo.TRANSSHIPMENT.POD, dbo.TRANSSHIPMENT.ORDERPRIORITY, 
                      dbo.TRANSSHIPMENT.EXPECTEDQTY, dbo.TRANSSHIPMENT.RECEIVEDQTY, dbo.TRANSSHIPMENT.EXPECTEDWEIGHT, 
                      dbo.TRANSSHIPMENT.RECEIVEWEIGHT, dbo.COMPANY.COMPANYNAME AS SOURCECOMPANYNAME, 
                      COMPANY_1.COMPANYNAME AS TARGETCOMPANYNAME, dbo.CONSIGNEE.CONSIGNEENAME, dbo.CONTACT.STREET1 AS SSTREET1, 
                      dbo.CONTACT.CITY AS SCITY, dbo.CONTACT.ZIP AS SZIP, dbo.CONTACT.CONTACT1NAME AS SCONTACT1NAME, 
                      dbo.CONTACT.CONTACT1PHONE AS SCONTACT1PHONE, CONTACT_1.STREET1 AS TSTREET1, CONTACT_1.CITY AS TCITY, CONTACT_1.ZIP AS TZIP, 
                      CONTACT_1.CONTACT1NAME AS TCONTACT1NAME, CONTACT_1.CONTACT1PHONE AS TCONTACT1PHONE
FROM         dbo.TRANSSHIPMENT INNER JOIN
                      dbo.COMPANY ON dbo.TRANSSHIPMENT.CONSIGNEE = dbo.COMPANY.CONSIGNEE AND 
                      dbo.TRANSSHIPMENT.TARGETCOMPANY = dbo.COMPANY.COMPANY AND 
                      dbo.TRANSSHIPMENT.TARGETCOMPANYTYPE = dbo.COMPANY.COMPANYTYPE INNER JOIN
                      dbo.COMPANY COMPANY_1 ON dbo.TRANSSHIPMENT.CONSIGNEE = COMPANY_1.CONSIGNEE AND 
                      dbo.TRANSSHIPMENT.SOURCECOMPANY = COMPANY_1.COMPANY AND 
                      dbo.TRANSSHIPMENT.SOURCECOMPANYTYPE = COMPANY_1.COMPANYTYPE INNER JOIN
                      dbo.CONSIGNEE ON dbo.TRANSSHIPMENT.CONSIGNEE = dbo.CONSIGNEE.CONSIGNEE INNER JOIN
                      dbo.CONTACT ON COMPANY_1.CONTACTID = dbo.CONTACT.CONTACTID INNER JOIN
                      dbo.CONTACT CONTACT_1 ON dbo.COMPANY.CONTACTID = CONTACT_1.CONTACTID

