<?xml version="1.0" encoding="UTF-8"?>
<!-- Receipt Close -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<BOM>
			<BO>
				<AdmInfo>
					<Object>15</Object>
				</AdmInfo>
				<ODLN>
					<row>
					<DocEntry></DocEntry>
					<DocNum></DocNum>
					<DocType>I</DocType>
					<CANCELED>N</CANCELED>
					<Handwrtten>N</Handwrtten>
					<Printed>N</Printed>
					<DocStatus>C</DocStatus>
					<InvntSttus>C</InvntSttus>
					<Transfered>N</Transfered>
					<ObjType>15</ObjType>
					<DocDate><xsl:value-of select="concat(substring(DATACOLLECTION/DATA/SHIPPEDDATE,6,4),substring(DATACOLLECTION/DATA/SHIPPEDDATE,1,2),substring(DATACOLLECTION/DATA/SHIPPEDDATE,4,2))"/></DocDate>
						<DocDueDate><xsl:value-of select="concat(substring(DATACOLLECTION/DATA/SHIPPEDDATE,6,4),substring(DATACOLLECTION/DATA/SHIPPEDDATE,1,2),substring(DATACOLLECTION/DATA/SHIPPEDDATE,4,2))"/></DocDueDate>
					<CardCode><xsl:value-of select="DATACOLLECTION/DATA/TARGETCOMPANY"/></CardCode>
					<CardName><xsl:value-of select="DATACOLLECTION/DATA/TARGETCOMPANYNAME"/></CardName>
					<Address></Address>
					<NumAtCard/>
					<VatPercent>0.000000</VatPercent>
					<VatSum>0.000000</VatSum>
					<VatSumFC>0.000000</VatSumFC>
					<DiscPrcnt>0.000000</DiscPrcnt>
					<DiscSum>0.000000</DiscSum>
					<DiscSumFC>0.000000</DiscSumFC>
					<DocCur>$</DocCur>
					<DocRate>1.000000</DocRate>
					<DocTotal>0.000000</DocTotal>
					<DocTotalFC>0.000000</DocTotalFC>
					<PaidToDate>0.000000</PaidToDate>
					<PaidFC>0.000000</PaidFC>
					<GrosProfit>0.000000</GrosProfit>
					<GrosProfFC>0.000000</GrosProfFC>
					<Ref1>1</Ref1>
					<Ref2/>
					<Comments><xsl:value-of select="DATACOLLECTION/DATA/NOTES"/></Comments>
					<JrnlMemo></JrnlMemo>
					<TransId>0</TransId>
					<ReceiptNum>0</ReceiptNum>
					<GroupNum>2</GroupNum>
					<DocTime></DocTime>
					<SlpCode></SlpCode>
					<TrnspCode>1</TrnspCode>
					<PartSupply>Y</PartSupply>
					<Confirmed>Y</Confirmed>
					<GrossBase></GrossBase>
					<ImportEnt>0</ImportEnt>
					<CreateTran>N</CreateTran>
					<SummryType>N</SummryType>
					<UpdInvnt>O</UpdInvnt>
					<UpdCardBal>N</UpdCardBal>
					<Instance>0</Instance>
					<Flags>0</Flags>
					<InvntDirec>E</InvntDirec>
					<CntctCode></CntctCode>
					<ShowSCN>N</ShowSCN>
					<FatherCard/>
					<SysRate>1.000000</SysRate>
					<CurSource>L</CurSource>
					<VatSumSy>0</VatSumSy>
					<DiscSumSy>0.000000</DiscSumSy>
					<DocTotalSy>0</DocTotalSy>
					<PaidSys>0</PaidSys>
					<FatherType>P</FatherType>
					<GrosProfSy>0.000000</GrosProfSy>
					<UpdateDate></UpdateDate>
					<IsICT>N</IsICT>
					<CreateDate><xsl:value-of select="concat(substring(DATACOLLECTION/DATA/SHIPPEDDATE,6,4),substring(DATACOLLECTION/DATA/SHIPPEDDATE,1,2),substring(DATACOLLECTION/DATA/SHIPPEDDATE,4,2))"/></CreateDate>
					<Volume>0</Volume>
					<VolUnit>5</VolUnit>
					<Weight>0</Weight>
					<WeightUnit>0</WeightUnit>
					<Series></Series>
					<TaxDate></TaxDate>
					<Filler/>
					<DataSource>O</DataSource>
					<StampNum/>
					<isCrin>N</isCrin>
					<FinncPriod>1</FinncPriod>
					<UserSign>1</UserSign>
					<selfInv>N</selfInv>
					<VatPaid>0</VatPaid>
					<VatPaidFC>0.000000</VatPaidFC>
					<VatPaidSys>0</VatPaidSys>
					<UserSign2>1</UserSign2>
					<WddStatus>-</WddStatus>
					<draftKey>0</draftKey>
					<TotalExpns>0.000000</TotalExpns>
					<TotalExpFC>0.000000</TotalExpFC>
					<TotalExpSC>0.000000</TotalExpSC>
					<DunnLevel>0</DunnLevel>
					<Address2></Address2>
					<LogInstanc>0</LogInstanc>
					<Exported>N</Exported>
					<StationID>0</StationID>
					<Indicator/>
					<NetProc>N</NetProc>
					<AqcsTax>0.000000</AqcsTax>
					<AqcsTaxFC>0.000000</AqcsTaxFC>
					<AqcsTaxSC>0.000000</AqcsTaxSC>
					<CashDiscPr>0.000000</CashDiscPr>
					<CashDiscnt>0.000000</CashDiscnt>
					<CashDiscFC>0.000000</CashDiscFC>
					<CashDiscSC>0.000000</CashDiscSC>
					<ShipToCode>Ship to</ShipToCode>
					<LicTradNum/>
					<PaymentRef/>
					<WTSum>0.000000</WTSum>
					<WTSumFC>0.000000</WTSumFC>
					<WTSumSC>0.000000</WTSumSC>
					<RoundDif>0.000000</RoundDif>
					<RoundDifFC>0.000000</RoundDifFC>
					<RoundDifSy>0.000000</RoundDifSy>
					<CheckDigit/>
					<Form1099>0</Form1099>
					<Box1099/>
					<submitted>N</submitted>
					<PoPrss>N</PoPrss>
					<Rounding>N</Rounding>
					<RevisionPo>N</RevisionPo>
					<Segment>0</Segment>
					<ReqDate/>
					<CancelDate/>
					<PickStatus>N</PickStatus>
					<Pick>N</Pick>
					<BlockDunn>N</BlockDunn>
					<PeyMethod>Outgoing Checks</PeyMethod>
					<PayBlock>N</PayBlock>
					<PayBlckRef>0</PayBlckRef>
					<MaxDscn>N</MaxDscn>
					<Reserve>N</Reserve>
					<Max1099>0</Max1099>
					<CntrlBnk/>
					<PickRmrk/>
					<ISRCodLine/>
					<ExpAppl>0.000000</ExpAppl>
					<ExpApplFC>0.000000</ExpApplFC>
					<ExpApplSC>0.000000</ExpApplSC>
					<Project/>
					<DeferrTax>N</DeferrTax>
					<LetterNum/>
					<FromDate/>
					<ToDate/>
					<WTApplied>0.000000</WTApplied>
					<WTAppliedF>0.000000</WTAppliedF>
					<BoeReserev>N</BoeReserev>
					<AgentCode/>
					<WTAppliedS>0.000000</WTAppliedS>
					<EquVatSum>0.000000</EquVatSum>
					<EquVatSumF>0.000000</EquVatSumF>
					<EquVatSumS>0.000000</EquVatSumS>
					<Installmnt>1</Installmnt>
					<VATFirst>N</VATFirst>
					<NnSbAmnt>0.000000</NnSbAmnt>
					<NnSbAmntSC>0.000000</NnSbAmntSC>
					<NbSbAmntFC>0.000000</NbSbAmntFC>
					<ExepAmnt>0.000000</ExepAmnt>
					<ExepAmntSC>0.000000</ExepAmntSC>
					<ExepAmntFC>0.000000</ExepAmntFC>
					<VatDate/>
					<CorrExt/>
					<CorrInv>0</CorrInv>
					<NCorrInv>0</NCorrInv>
					<CEECFlag/>
					<BaseAmnt>0.000000</BaseAmnt>
					<BaseAmntSC>0.000000</BaseAmntSC>
					<BaseAmntFC>0.000000</BaseAmntFC>
					<CtlAccount></CtlAccount>
					<BPLId>0</BPLId>
					<BPLName/>
					<VATRegNum/>
					<TxInvRptNo/>
					<TxInvRptDt/>
					<KVVATCode/>
					<WTDetails/>
					<SumAbsId>-1</SumAbsId>
					<SumRptDate/>
					<PIndicator>Default</PIndicator>
					<ManualNum/>
					<UseShpdGd>N</UseShpdGd>
					<BaseVtAt>0.000000</BaseVtAt>
					<BaseVtAtSC>0.000000</BaseVtAtSC>
					<BaseVtAtFC>0.000000</BaseVtAtFC>
					<NnSbVAt>0.000000</NnSbVAt>
					<NnSbVAtSC>0.000000</NnSbVAtSC>
					<NbSbVAtFC>0.000000</NbSbVAtFC>
					<ExptVAt>0.000000</ExptVAt>
					<ExptVAtSC>0.000000</ExptVAtSC>
					<ExptVAtFC>0.000000</ExptVAtFC>
					<LYPmtAt>0.000000</LYPmtAt>
					<LYPmtAtSC>0.000000</LYPmtAtSC>
					<LYPmtAtFC>0.000000</LYPmtAtFC>
					<ExpAnSum>0.000000</ExpAnSum>
					<ExpAnSys>0.000000</ExpAnSys>
					<ExpAnFrgn>0.000000</ExpAnFrgn>
					<DocSubType>--</DocSubType>
					<DpmStatus>O</DpmStatus>
					<DpmAmnt>0.000000</DpmAmnt>
					<DpmAmntSC>0.000000</DpmAmntSC>
					<DpmAmntFC>0.000000</DpmAmntFC>
					<DpmDrawn>N</DpmDrawn>
					<DpmPrcnt>0.000000</DpmPrcnt>
					<PaidSum>0.000000</PaidSum>
					<PaidSumFc>0.000000</PaidSumFc>
					<PaidSumSc>0.000000</PaidSumSc>
					<FolioPref/>
					<FolioNum>0</FolioNum>
					<DpmAppl>0.000000</DpmAppl>
					<DpmApplFc>0.000000</DpmApplFc>
					<DpmApplSc>0.000000</DpmApplSc>
					<LPgFolioN>0</LPgFolioN>
					<Header/>
					<Footer/>
					<Posted>Y</Posted>
					<OwnerCode>0</OwnerCode>
					<BPChCode/>
					<BPChCntc>0</BPChCntc>
					<PayToCode>Pay To</PayToCode>
					<IsPaytoBnk>N</IsPaytoBnk>
					<BnkCntry/>
					<BankCode/>
					<BnkAccount/>
					<BnkBranch/>
					<isIns>N</isIns>
					<TrackNo/>
					<VersionNum></VersionNum>
					<LangCode>3</LangCode>
					<BPNameOW>N</BPNameOW>
					<BillToOW>N</BillToOW>
					<ShipToOW>N</ShipToOW>
					<RetInvoice>N</RetInvoice>
					<ClsDate/>
					<MInvNum>0</MInvNum>
					<MInvDate/>
					<SeqCode>0</SeqCode>
					<Serial>0</Serial>
					<SeriesStr/>
					<SubStr/>
					<Model>0</Model>
					<TaxOnExp>0.000000</TaxOnExp>
					<TaxOnExpFc>0.000000</TaxOnExpFc>
					<TaxOnExpSc>0.000000</TaxOnExpSc>
					<TaxOnExAp>0.000000</TaxOnExAp>
					<TaxOnExApF>0.000000</TaxOnExApF>
					<TaxOnExApS>0.000000</TaxOnExApS>
					<LastPmnTyp/>
					<LndCstNum>0</LndCstNum>
					<UseCorrVat>N</UseCorrVat>
					<BlkCredMmo>N</BlkCredMmo>
					<OpenForLaC>Y</OpenForLaC>
				</row>
				</ODLN>
				<DLN1>
					<xsl:for-each select="DATACOLLECTION/DATA/LINES/LINE[QTYSHIPPED &gt; 0]">					
					<row>
						<DocEntry></DocEntry>
						<LineNum><xsl:value-of select="ORDERLINE"/></LineNum>
						<TargetType>15</TargetType>
						<TrgetEntry>1</TrgetEntry>
						<BaseRef/>
						<BaseType>17</BaseType>
						<BaseEntry><xsl:value-of select="ORDERID"/></BaseEntry>
						<BaseLine><xsl:value-of select="ORDERLINE"/></BaseLine>
						<LineStatus>O</LineStatus>
						<ItemCode><xsl:value-of select="SKU"/></ItemCode>
						<Dscription></Dscription>
						<Quantity><xsl:value-of select="QTYSHIPPED"/></Quantity>
						<ShipDate></ShipDate>
						<OpenQty>0.000000</OpenQty>
						<Price>0</Price>
						<Currency></Currency>
						<Rate>0.000000</Rate>
						<DiscPrcnt>0.000000</DiscPrcnt>
						<LineTotal>0</LineTotal>
						<TotalFrgn>0.000000</TotalFrgn>
						<OpenSum>0</OpenSum>
						<OpenSumFC>0.000000</OpenSumFC>
						<VendorNum/>
						<SerialNum/>
						<WhsCode>01</WhsCode>
						<SlpCode>-1</SlpCode>
						<Commission>0.000000</Commission>
						<TreeType>N</TreeType>
						<AcctCode></AcctCode>
						<TaxStatus>Y</TaxStatus>
						<GrossBuyPr>0.000000</GrossBuyPr>
						<PriceBefDi>0</PriceBefDi>
						<DocDate>20060101</DocDate>
						<Flags>0</Flags>
						<OpenCreQty>0.000000</OpenCreQty>
						<UseBaseUn>N</UseBaseUn>
						<SubCatNum/>
						<BaseCard></BaseCard>
						<TotalSumSy>0</TotalSumSy>
						<OpenSumSys>0</OpenSumSys>
						<InvntSttus>C</InvntSttus>
						<OcrCode/>
						<Project/>
						<CodeBars/>
						<VatPrcnt>0</VatPrcnt>
						<VatGroup/>
						<PriceAfVAT>0</PriceAfVAT>
						<Height1>0</Height1>
						<Hght1Unit>0</Hght1Unit>
						<Height2>0.000000</Height2>
						<Hght2Unit>0</Hght2Unit>
						<Width1>0</Width1>
						<Wdth1Unit>0</Wdth1Unit>
						<Width2>0.000000</Width2>
						<Wdth2Unit>0</Wdth2Unit>
						<Length1>0</Length1>
						<Len1Unit>0</Len1Unit>
						<length2>0.000000</length2>
						<Len2Unit>0</Len2Unit>
						<Volume>0</Volume>
						<VolUnit>0</VolUnit>
						<Weight1>0</Weight1>
						<Wght1Unit>0</Wght1Unit>
						<Weight2>0.000000</Weight2>
						<Wght2Unit>0</Wght2Unit>
						<Factor1>0</Factor1>
						<Factor2>0</Factor2>
						<Factor3>0</Factor3>
						<Factor4>0</Factor4>
						<PackQty>0</PackQty>
						<UpdInvntry>Y</UpdInvntry>
						<BaseDocNum>0</BaseDocNum>
						<BaseAtCard/>
						<SWW/>
						<VatSum>0</VatSum>
						<VatSumFrgn>0.000000</VatSumFrgn>
						<VatSumSy>0</VatSumSy>
						<FinncPriod>1</FinncPriod>
						<ObjType>20</ObjType>
						<LogInstanc>0</LogInstanc>
						<BlockNum/>
						<ImportLog/>
						<DedVatSum>0</DedVatSum>
						<DedVatSumF>0.000000</DedVatSumF>
						<DedVatSumS>0</DedVatSumS>
						<IsAqcuistn>N</IsAqcuistn>
						<DistribSum>0.000000</DistribSum>
						<DstrbSumFC>0.000000</DstrbSumFC>
						<DstrbSumSC>0.000000</DstrbSumSC>
						<GrssProfit>0.000000</GrssProfit>
						<GrssProfSC>0.000000</GrssProfSC>
						<GrssProfFC>0.000000</GrssProfFC>
						<VisOrder>0</VisOrder>
						<INMPrice>0</INMPrice>
						<PoTrgNum>0</PoTrgNum>
						<PoTrgEntry/>
						<DropShip>N</DropShip>
						<PoLineNum>0</PoLineNum>
						<Address></Address>
						<TaxCode></TaxCode>
						<TaxType>N</TaxType>
						<OrigItem/>
						<BackOrdr/>
						<FreeTxt/>
						<PickStatus>N</PickStatus>
						<PickOty>0.000000</PickOty>
						<PickIdNo>0</PickIdNo>
						<TrnsCode>0</TrnsCode>
						<VatAppld>0</VatAppld>
						<VatAppldFC>0.000000</VatAppldFC>
						<VatAppldSC>0</VatAppldSC>
						<BaseQty>0.000000</BaseQty>
						<BaseOpnQty>0.000000</BaseOpnQty>
						<VatDscntPr>0.000000</VatDscntPr>
						<WtLiable>N</WtLiable>
						<DeferrTax>N</DeferrTax>
						<EquVatPer>0.000000</EquVatPer>
						<EquVatSum>0.000000</EquVatSum>
						<EquVatSumF>0.000000</EquVatSumF>
						<EquVatSumS>0.000000</EquVatSumS>
						<LineVat>0</LineVat>
						<LineVatlF>0.000000</LineVatlF>
						<LineVatS>0</LineVatS>
						<unitMsr/>
						<NumPerMsr>0</NumPerMsr>
						<CEECFlag>S</CEECFlag>
						<ToStock>0.000000</ToStock>
						<ToDiff>0.000000</ToDiff>
						<ExciseAmt>0.000000</ExciseAmt>
						<TaxPerUnit>0.000000</TaxPerUnit>
						<TotInclTax>0.000000</TotInclTax>
						<CountryOrg/>
						<StckDstSum>0.000000</StckDstSum>
						<ReleasQtty>0.000000</ReleasQtty>
						<LineType>R</LineType>
						<TranType/>
						<Text/>
						<OwnerCode>0</OwnerCode>
						<StockPrice>0.000000</StockPrice>
						<ConsumeFCT>N</ConsumeFCT>
						<LstByDsSum>0.000000</LstByDsSum>
						<StckINMPr>0.000000</StckINMPr>
						<LstBINMPr>0.000000</LstBINMPr>
						<StckDstFc>0.000000</StckDstFc>
						<StckDstSc>0.000000</StckDstSc>
						<LstByDsFc>0.000000</LstByDsFc>
						<LstByDsSc>0.000000</LstByDsSc>
						<StockSum>0.000000</StockSum>
						<StockSumFc>0.000000</StockSumFc>
						<StockSumSc>0.000000</StockSumSc>
						<StckSumApp>0.000000</StckSumApp>
						<StckAppFc>0.000000</StckAppFc>
						<StckAppSc>0.000000</StckAppSc>
						<ShipToCode/>
						<ShipToDesc/>
						<StckAppD>0.000000</StckAppD>
						<StckAppDFC>0.000000</StckAppDFC>
						<StckAppDSC>0.000000</StckAppDSC>
						<BasePrice>E</BasePrice>
						<GTotal>0</GTotal>
						<GTotalFC>0.000000</GTotalFC>
						<GTotalSC>0</GTotalSC>
						<DistribExp>Y</DistribExp>
						<DescOW>N</DescOW>
						<DetailsOW>N</DetailsOW>
						<GrossBase>0</GrossBase>
						<VatWoDpm>0.000000</VatWoDpm>
						<VatWoDpmFc>0.000000</VatWoDpmFc>
						<VatWoDpmSc>0.000000</VatWoDpmSc>
						<CFOPCode/>
						<CSTCode/>
						<Usage>0</Usage>
						<TaxOnly>N</TaxOnly>
						<WtCalced>N</WtCalced>
						<QtyToShip>0.000000</QtyToShip>
						<DelivrdQty>0.000000</DelivrdQty>
						<OrderedQty>0.000000</OrderedQty>
						<CogsOcrCod/>
						<CiOppLineN>-1</CiOppLineN>
						<CogsAcct/>
						<ChgAsmBoMW/>
						<ActDelDate/>
					</row>
					</xsl:for-each>
				</DLN1>
			</BO>
		</BOM>
	</xsl:template>
</xsl:stylesheet>
