'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PriceFactorCalcParam

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Screen1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents Screen1 As Global.WMS.WebCtrls.WebCtrls.Screen

    '''<summary>
    '''TEBILLINGPRICEFACTORINDEX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TEBILLINGPRICEFACTORINDEX As Global.Made4Net.WebControls.TableEditor

    '''<summary>
    '''DTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DTC As Global.Made4Net.WebControls.DataTabControl

    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''TS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents TS As Global.Made4Net.WebControls.TabStrip

    '''<summary>
    '''Tbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tbl As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''TEBILLINGFIXEDPRICEFACTORPARAMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TEBILLINGFIXEDPRICEFACTORPARAMS As Global.Made4Net.WebControls.TableEditor

    '''<summary>
    '''Tbl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tbl1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''TEBILLINGDAILYPRICEFACTORPARAMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TEBILLINGDAILYPRICEFACTORPARAMS As Global.Made4Net.WebControls.TableEditor

    '''<summary>
    '''TEBILLINGDAILYPRICEFACTORPARAMSVALUES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TEBILLINGDAILYPRICEFACTORPARAMSVALUES As Global.Made4Net.WebControls.TableEditor

    '''<summary>
    '''DC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DC2 As Global.Made4Net.WebControls.DataConnector
End Class
