'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Simulators

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadScriptManager2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager2 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''Screen1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents Screen1 As Global.WMS.WebCtrls.WebCtrls.Screen

    '''<summary>
    '''DTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DTC As Global.Made4Net.WebControls.DataTabControl

    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''TS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents TS As Global.Made4Net.WebControls.TabStrip

    '''<summary>
    '''Tbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tbl As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''tblPlanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPlanner As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''rdbWave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbWave As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbOrders As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblWave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWave As Global.Made4Net.WebControls.Label

    '''<summary>
    '''txtWave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents txtWave As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''lblCons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCons As Global.Made4Net.WebControls.Label

    '''<summary>
    '''txtCons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents txtCons As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''lblOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrder As Global.Made4Net.WebControls.Label

    '''<summary>
    '''txtOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents txtOrder As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''btnSimulatePlanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSimulatePlanner As Global.Made4Net.WebControls.Button

    '''<summary>
    '''tblTaskManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblTaskManager As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUser As Global.Made4Net.WebControls.Label

    '''<summary>
    '''taUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents taUserID As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''lblMHType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMHType As Global.Made4Net.WebControls.Label

    '''<summary>
    '''taMHEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents taMHEquip As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''LabeInitalLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabeInitalLocation As Global.Made4Net.WebControls.Label

    '''<summary>
    '''taInitLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents taInitLoc As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''btnTaskManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTaskManager As Global.Made4Net.WebControls.Button

    '''<summary>
    '''TABLE4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TABLE4 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''taLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents taLoad As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''LabeUsrId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabeUsrId As Global.Made4Net.WebControls.Label

    '''<summary>
    '''TypeAheadBoxUsrId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents TypeAheadBoxUsrId As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''taContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents taContainer As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.Made4Net.WebControls.Button

    '''<summary>
    '''TABLE3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TABLE3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''rdbReplZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbReplZone As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbReplPicking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbReplPicking As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocation As Global.Made4Net.WebControls.Label

    '''<summary>
    '''taLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents taLocation As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''lblWareahousearea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWareahousearea As Global.Made4Net.WebControls.Label

    '''<summary>
    '''taWareahousearea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents taWareahousearea As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''lblPutRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPutRegion As Global.Made4Net.WebControls.Label

    '''<summary>
    '''taPutRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents taPutRegion As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''lblReplSku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReplSku As Global.Made4Net.WebControls.Label

    '''<summary>
    '''taSKU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents taSKU As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''btnReplenisment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReplenisment As Global.Made4Net.WebControls.Button

    '''<summary>
    '''TABLEDISTANCE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TABLEDISTANCE As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.Made4Net.WebControls.Label

    '''<summary>
    '''TypeAheadBoxLocationFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents TypeAheadBoxLocationFrom As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.Made4Net.WebControls.Label

    '''<summary>
    '''TypeAheadBoxLocationTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents TypeAheadBoxLocationTo As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.Made4Net.WebControls.Label

    '''<summary>
    '''TextBoxHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxHeight As Global.Made4Net.WebControls.TextBox

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.Made4Net.WebControls.Label

    '''<summary>
    '''TypeAheadBoxHandlingEquipment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    <CLSCompliant(False)>
    Protected WithEvents TypeAheadBoxHandlingEquipment As Global.Made4Net.WebControls.TypeAheadBox

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.Made4Net.WebControls.Label

    '''<summary>
    '''CheckBoxUnidirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxUnidirection As Global.Made4Net.WebControls.CheckBox

    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.Made4Net.WebControls.Button

    '''<summary>
    '''Button3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button3 As Global.Made4Net.WebControls.Button

    '''<summary>
    '''chkisDeleteLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkisDeleteLog As Global.Made4Net.WebControls.CheckBox

    '''<summary>
    '''logFiletxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logFiletxt As Global.Made4Net.WebControls.TextBox
End Class
