<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2011sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_BOM" select="BOM"/>
		<DATACOLLECTION>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">
				<xsl:value-of select="'C:/Projects/SCExpertTrunk/SCExpertConnectSBOPlugin/XSLMaps/Documents/SalesOrders/OutboundScheme.xsd'"/>
			</xsl:attribute>
			<DATA>
				<xsl:for-each select="$var1_BOM">
					<CONSIGNEE>
						<xsl:value-of select="/.."/>
					</CONSIGNEE>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<ORDERID>
						<xsl:value-of select="/.."/>
					</ORDERID>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<ORDERTYPE>
						<xsl:value-of select="/.."/>
					</ORDERTYPE>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<REFERENCEORD>
						<xsl:value-of select="/.."/>
					</REFERENCEORD>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<TARGETCOMPANY>
						<xsl:value-of select="/.."/>
					</TARGETCOMPANY>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<COMPANYTYPE>
						<xsl:value-of select="/.."/>
					</COMPANYTYPE>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<STATUS>
						<xsl:value-of select="/.."/>
					</STATUS>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<CREATEDATE>
						<xsl:value-of select="/.."/>
					</CREATEDATE>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<NOTES>
						<xsl:value-of select="/.."/>
					</NOTES>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<STAGINGLANE>
						<xsl:value-of select="/.."/>
					</STAGINGLANE>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<REQUESTEDDATE>
						<xsl:value-of select="/.."/>
					</REQUESTEDDATE>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<SCHEDULEDDATE>
						<xsl:value-of select="/.."/>
					</SCHEDULEDDATE>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<SHIPPEDDATE>
						<xsl:value-of select="/.."/>
					</SHIPPEDDATE>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<SHIPMENT>
						<xsl:value-of select="/.."/>
					</SHIPMENT>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<STOPNUMBER>
						<xsl:value-of select="/.."/>
					</STOPNUMBER>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<ORDERPRIORITY>
						<xsl:value-of select="/.."/>
					</ORDERPRIORITY>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<ROUTE>
						<xsl:value-of select="/.."/>
					</ROUTE>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<LOADINGSEQ>
						<xsl:value-of select="/.."/>
					</LOADINGSEQ>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<WAVE>
						<xsl:value-of select="/.."/>
					</WAVE>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<ROUTINGSET>
						<xsl:value-of select="/.."/>
					</ROUTINGSET>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<STATUSDATE>
						<xsl:value-of select="/.."/>
					</STATUSDATE>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<HOSTORDERID>
						<xsl:value-of select="/.."/>
					</HOSTORDERID>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<DELIVERYSTATUS>
						<xsl:value-of select="/.."/>
					</DELIVERYSTATUS>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<TARGETCOMPANYNAME>
						<xsl:value-of select="/.."/>
					</TARGETCOMPANYNAME>
				</xsl:for-each>
				<xsl:for-each select="$var1_BOM">
					<SHIPTO>
						<xsl:value-of select="/.."/>
					</SHIPTO>
				</xsl:for-each>
				<LINES>
					<LINE>
						<xsl:for-each select="$var1_BOM">
							<ORDERLINE>
								<xsl:value-of select="/.."/>
							</ORDERLINE>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<REFERENCEORDLINE>
								<xsl:value-of select="/.."/>
							</REFERENCEORDLINE>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<SKU>
								<xsl:value-of select="/.."/>
							</SKU>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<INVENTORYSTATUS>
								<xsl:value-of select="/.."/>
							</INVENTORYSTATUS>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<QTYORIGINAL>
								<xsl:value-of select="/.."/>
							</QTYORIGINAL>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<QTYMODIFIED>
								<xsl:value-of select="/.."/>
							</QTYMODIFIED>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<QTYALLOCATED>
								<xsl:value-of select="/.."/>
							</QTYALLOCATED>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<QTYPICKED>
								<xsl:value-of select="/.."/>
							</QTYPICKED>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<QTYSTAGED>
								<xsl:value-of select="/.."/>
							</QTYSTAGED>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<QTYVERIFIED>
								<xsl:value-of select="/.."/>
							</QTYVERIFIED>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<QTYLOADED>
								<xsl:value-of select="/.."/>
							</QTYLOADED>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<QTYSHIPPED>
								<xsl:value-of select="/.."/>
							</QTYSHIPPED>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<EXPLOADEDFLAG>
								<xsl:value-of select="/.."/>
							</EXPLOADEDFLAG>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<INPUTQTY>
								<xsl:value-of select="/.."/>
							</INPUTQTY>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<INPUTUOM>
								<xsl:value-of select="/.."/>
							</INPUTUOM>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<UNITPRICE>
								<xsl:value-of select="/.."/>
							</UNITPRICE>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<INPUTSKU>
								<xsl:value-of select="/.."/>
							</INPUTSKU>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<SKUVOLUME>
								<xsl:value-of select="/.."/>
							</SKUVOLUME>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<SKUWEIGHT>
								<xsl:value-of select="/.."/>
							</SKUWEIGHT>
						</xsl:for-each>
						<xsl:for-each select="$var1_BOM">
							<NOTES>
								<xsl:value-of select="/.."/>
							</NOTES>
						</xsl:for-each>
					</LINE>
				</LINES>
			</DATA>
		</DATACOLLECTION>
	</xsl:template>
</xsl:stylesheet>
